### ISSUE TITLE
Override query Type object

### ISSUE THREAD

**Issue by jardix22** [recidive/choko#265] opened 2015-03-28 23:48 UTC
We are using Type Content to create subtypes as Media, Video and Audio. I have bug when try create pages to list subtypes.

*video-list.page.json*
``` 
{
  "type": "list",
  "title": "Videos",
  "description": "The videos page.",
  "itemType": "content",
  "path": "/media/videos",
  "query": {
    "type": "video"
  },
  "listStyle": "list-group",
  "itemDisplay": "list-group-item"
}
```

Then in the  line [180] (https://github.com/recidive/choko/blob/master/applications/default/public/js/controllers.js#L180) of choko controller, we override the type into the query object with the query object from the *video-list.page.json*.  

``` 
console.log(query) // {type: 'content'}
console.log($scope.view.query) // {type: 'video'}

 if ($scope.view.query) {
     angular.extend(query, $scope.view.query);
 }

console.log(query) // {type: 'video'} 
```
In the end this create a bad url.

**Comment by recidive** [comment] 2015-03-30 22:05
Duplicate of #199.

**Closed by recidive** 2015-03-30 22:05 UTC
Labels: duplicate
